cmake_minimum_required(VERSION 4.1)
project(OOPaD_2026)

set(CMAKE_CXX_STANDARD 20)

add_executable(OOPaD_2026 src/main.cpp
        libs/Menu.cpp
        libs/Menu.h
        src/Controller/LabsMenu.cpp
        src/Controller/LabsMenu.h
        libs/CheckInput.cpp
        libs/CheckInput.h
        libs/TerminalController.cpp
        libs/TerminalController.h
)

add_executable(laba-1 labs/laba-1/src/laba-1.cpp
        libs/Menu.cpp
        libs/Menu.h
        libs/CheckInput.cpp
        libs/CheckInput.h
        libs/TerminalController.cpp
        libs/TerminalController.h
        labs/laba-1/src/Entities/LinkedListInt.cpp
        labs/laba-1/src/Entities/LinkedListInt.h
        labs/laba-1/src/Entities/LinkedListString.cpp
        labs/laba-1/src/Entities/LinkedListString.h
        labs/laba-1/src/Controller/FirstLabMenu.cpp
        labs/laba-1/src/Controller/FirstLabMenu.h
        labs/laba-1/src/Controller/ListMenu.cpp
        labs/laba-1/src/Controller/ListMenu.h
        labs/laba-1/src/Controller/ListIntController.cpp
        labs/laba-1/src/Controller/ListIntController.h
        labs/laba-1/src/Controller/ListStringController.cpp
        labs/laba-1/src/Controller/ListStringController.h
)
add_executable(laba-2 labs/laba-2/src/laba-2.cpp
        labs/laba-2/src/Controller/SecondLabMenu.cpp
        labs/laba-2/src/Controller/SecondLabMenu.h
        labs/laba-2/src/Entities/Array.cpp
        labs/laba-2/src/Entities/Array.h
        labs/laba-2/src/Controller/Manipulator.cpp
        labs/laba-2/src/Controller/Manipulator.h
        libs/CheckInput.cpp
        libs/CheckInput.h
        libs/TerminalController.cpp
        libs/TerminalController.h
        libs/Menu.cpp
        libs/Menu.h
)
add_executable(laba-3 labs/laba-3/src/laba-3.cpp
        labs/laba-3/src/Controller/ThirdLabMenu.cpp
        labs/laba-3/src/Controller/ThirdLabMenu.h
        labs/laba-3/src/Entity/Distance.cpp
        labs/laba-3/src/Entity/Distance.h
        labs/laba-3/src/Controller/CheckInputThirdLab.cpp
        labs/laba-3/src/Controller/CheckInputThirdLab.h
        libs/TerminalController.cpp
        libs/TerminalController.h
        libs/Menu.cpp
        libs/Menu.h
)
add_executable(laba-4 labs/laba-4/src/laba-4.cpp
        labs/laba-4/src/Controller/FourthLabMenu.cpp
        labs/laba-4/src/Controller/FourthLabMenu.h
        libs/TerminalController.cpp
        libs/TerminalController.h
        libs/Menu.cpp
        libs/Menu.h
        libs/CheckInput.cpp
        libs/CheckInput.h
        labs/laba-4/src/Entity/LocalDateTime.cpp
        labs/laba-4/src/Entity/LocalDateTime.h
        labs/laba-4/src/Entity/LocalDate.cpp
        labs/laba-4/src/Entity/LocalDate.h
        labs/laba-4/src/Entity/LocalTime.cpp
        labs/laba-4/src/Entity/LocalTime.h
        labs/laba-4/src/Entity/DateTimeBase.cpp
        labs/laba-4/src/Entity/DateTimeBase.h
        labs/laba-4/src/Entity/Route.cpp
        labs/laba-4/src/Entity/Route.h
        labs/laba-4/src/Controller/RouteController.cpp
        labs/laba-4/src/Controller/RouteController.h
)
add_executable(laba-5 labs/laba-5/laba-5.cpp
        labs/laba-5/Entities/Circle.cpp
        labs/laba-5/Entities/Circle.h
        labs/laba-5/Entities/Square.cpp
        labs/laba-5/Entities/Square.h
        labs/laba-5/Entities/Triangle.cpp
        labs/laba-5/Entities/Triangle.h
        labs/laba-5/Entities/Shape.cpp
        labs/laba-5/Entities/Shape.h
        labs/laba-5/Entities/Pyramid.cpp
        labs/laba-5/Entities/Pyramid.h
        labs/laba-5/Controller/FifthLabMenu.cpp
        labs/laba-5/Controller/FifthLabMenu.h
        labs/laba-5/Controller/ShapesController.cpp
        labs/laba-5/Controller/ShapesController.h
        libs/TerminalController.cpp
        libs/TerminalController.h
        libs/Menu.cpp
        libs/Menu.h
        libs/CheckInput.cpp
        libs/CheckInput.h
)
add_executable(laba-6 labs/laba-6/laba-6.cpp
        labs/laba-6/Entities/Process.cpp
        labs/laba-6/Entities/Process.h
        labs/laba-6/Entities/HumanActivity.cpp
        labs/laba-6/Entities/HumanActivity.h
        labs/laba-6/Entities/Game.cpp
        labs/laba-6/Entities/Game.h
        labs/laba-6/Entities/Esports.cpp
        labs/laba-6/Entities/Esports.h
        labs/laba-6/Entities/CompetitiveSport.cpp
        labs/laba-6/Entities/CompetitiveSport.h
        libs/TerminalController.h
        libs/TerminalController.cpp
        libs/CheckInput.h
        libs/CheckInput.cpp
        libs/Menu.h
        libs/Menu.cpp
        libs/Date.h
        libs/Date.cpp
        labs/laba-6/Controller/SixthLabMenu.cpp
        labs/laba-6/Controller/SixthLabMenu.h
        labs/laba-6/Controller/EntitiesManager.cpp
        labs/laba-6/Controller/EntitiesManager.h
)

add_executable(laba-7 labs/laba-7/laba-7.cpp
        libs/TerminalController.h
        libs/TerminalController.cpp
        libs/CheckInput.h
        libs/CheckInput.cpp
        libs/Menu.h
        libs/Menu.cpp
        labs/laba-7/Controller/SevenLabMenu.cpp
        labs/laba-7/Controller/SevenLabMenu.h
        labs/laba-7/Entities/Catalog.h
        labs/laba-7/Entities/Organisation.cpp
        labs/laba-7/Entities/Organisation.h
        labs/laba-7/Entities/Book.cpp
        labs/laba-7/Entities/Book.h
        labs/laba-7/Entities/Reader.cpp
        labs/laba-7/Entities/Reader.h
        labs/laba-7/Entities/Subscription.cpp
        labs/laba-7/Entities/Subscription.h
        labs/laba-7/Entities/Employee.cpp
        labs/laba-7/Entities/Employee.h
        labs/laba-7/Entities/Library.cpp
        labs/laba-7/Entities/Library.h
        labs/laba-7/Controller/LibraryManager.cpp
        labs/laba-7/Controller/LibraryManager.h
)

add_executable(laba-8 labs/laba-8/laba-8.cpp
        libs/TerminalController.h
        libs/TerminalController.cpp
        libs/CheckInput.h
        libs/CheckInput.cpp
        libs/Menu.h
        libs/Menu.cpp
        labs/laba-8/Controller/EighthLabMenu.cpp
        labs/laba-8/Controller/EighthLabMenu.h
        labs/laba-8/Entities/Catalog.h
        labs/laba-8/Entities/Organisation.cpp
        labs/laba-8/Entities/Organisation.h
        labs/laba-8/Entities/Book.cpp
        labs/laba-8/Entities/Book.h
        labs/laba-8/Entities/Reader.cpp
        labs/laba-8/Entities/Reader.h
        labs/laba-8/Entities/Subscription.cpp
        labs/laba-8/Entities/Subscription.h
        labs/laba-8/Entities/Employee.cpp
        labs/laba-8/Entities/Employee.h
        labs/laba-8/Entities/Library.cpp
        labs/laba-8/Entities/Library.h
        labs/laba-8/Controller/LibraryManager.cpp
        labs/laba-8/Controller/LibraryManager.h
        labs/laba-8/Entities/Transaction.h
        labs/laba-8/Controller/TransactionMenu.cpp
        labs/laba-8/Controller/TransactionMenu.h
)

add_executable(laba-9 labs/laba-9/laba-9.cpp
        libs/TerminalController.h
        libs/TerminalController.cpp
        libs/CheckInput.h
        libs/CheckInput.cpp
        libs/Menu.h
        libs/Menu.cpp
        labs/laba-9/Controller/NinthLabMenu.cpp
        labs/laba-9/Controller/NinthLabMenu.h
        labs/laba-9/Entities/Product.cpp
        labs/laba-9/Entities/Product.h
        labs/laba-9/Entities/BuildingMaterial.cpp
        labs/laba-9/Entities/BuildingMaterial.h
        labs/laba-9/Entities/Tool.cpp
        labs/laba-9/Entities/Tool.h
        labs/laba-9/Entities/Warehouse.cpp
        labs/laba-9/Entities/Warehouse.h
        labs/laba-9/Entities/OrderItem.cpp
        labs/laba-9/Entities/OrderItem.h
        labs/laba-9/Entities/Order.cpp
        labs/laba-9/Entities/Order.h
        labs/laba-9/Entities/Store.cpp
        labs/laba-9/Entities/Store.h
        labs/laba-9/Exceptions/StoreException.cpp
        labs/laba-9/Exceptions/StoreException.h
        labs/laba-9/Exceptions/OutOfStockException.cpp
        labs/laba-9/Exceptions/OutOfStockException.h
        labs/laba-9/Exceptions/InvalidQuantityException.cpp
        labs/laba-9/Exceptions/InvalidQuantityException.h
        labs/laba-9/Exceptions/InvalidPriceException.cpp
        labs/laba-9/Exceptions/InvalidPriceException.h
        labs/laba-9/Exceptions/EmptyOrderException.cpp
        labs/laba-9/Exceptions/EmptyOrderException.h
        labs/laba-9/Controller/StoreManager.cpp
        labs/laba-9/Controller/StoreManager.h
        labs/laba-9/Controller/OrderMenu.cpp
        labs/laba-9/Controller/OrderMenu.h
)

